[build]
  command = "npm run build:prod"
  functions = "functions"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/server/"
  status = 200
  force = true

[[redirects]]
  from = "/artist/* page=:page"
  to = "/.netlify/functions/server/artist:splat?:page"
  status = 200
  force = true

[[redirects]]
  from = "/release/*"
  to = "/.netlify/functions/server/release:splat"
  status = 200
  force = true

[[redirects]]
  from = "/master/*"
  to = "/.netlify/functions/server/master:splat"
  status = 200
  force = true

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/server/search"
  status = 200
  force = true
